
.CSEG

.DEF TEMP_1 = R16
.DEF TEMP_2 = R17

IDLE_RUN:
	
	;Procesar buffer GRBL
	
	;Verificar si termina en \n
	POINT_Y_TO_END_OF_BUFFER GRBL_BUFFER, GRBL_BUFFER_POINTER
	
	LD TEMP_1, Y
	
	CPI TEMP_1, '\n'
	BRNE IDLE_GRBL_CONTINUE
		
		RCALL IDLE_GRBL_PROCESS_LINE
	
	IDLE_GRBL_CONTINUE:
	
	;Si hay cambio de estado terminar
	LDS TEMP_1, CURRENT_STATE
	CPI TEMP_1, STATE_IDLE
	BRNE IDLE_END

	;Verificar connección PC
	
	;Verificar si termina en \n
	POINT_Y_TO_END_OF_BUFFER USB_BUFFER, USB_BUFFER_POINTER
	
	LD TEMP_1, Y
	
	CPI TEMP_1, '\n'
	BRNE IDLE_USB_CONTINUE
	
		;Procesar linea de USB
	
	IDLE_USB_CONTINUE:
	
	;Procesar botones
	CALL BUTTONS_READ
	MOV R10, R16
	MOV R11, R16
	
	ANDI R16, (1<<BUTTONS_CHANGE) ; Si es el boton de cambiar
	BREQ IDLE_TEST_CONFIRM
	
		LDS R11, GGR
		LDI R16, (1<<UIS)
		EOR R11, R16 ;Invertir estado de UI
		STS GGR, R11 ;Guardar
		
		RJMP IDLE_BUTTONS_CONTINUE
	IDLE_TEST_CONFIRM:
		
		;Logica de cambio de estado
		
	IDLE_BUTTONS_CONTINUE:
	
	;Actualizar UI
	
	IDLE_END:

	RET


;Subrutina para procesar una linea de GRBL

IDLE_GRBL_PROCESS_LINE:
	
	;Comparar con error

	LDI XL, LOW(GRBL_BUFFER)
	LDI XH, HIGH(GRBL_BUFFER)

	LDI ZL, LOW(GRBL_ERROR<<1)
	LDI ZH, HIGH(GRBL_ERROR<<1)

	CALL STRING_COMPARE_P

	BREQ IDLE_GRBL_PROCESS_CONTINUE

		LDI TEMP_1, STATE_ERROR
		STS CURRENT_STATE, TEMP_1

	IDLE_GRBL_PROCESS_CONTINUE:

	BUFFER_CLEAR GRBL_BUFFER_POINTER

	RET


;Subrutina para procesar una linea de GRBL

IDLE_USB_PROCESS_LINE:
	
	;Comparar con error

	LDI XL, LOW(USB_BUFFER)
	LDI XH, HIGH(USB_BUFFER)

	LDI ZL, LOW(USB_TICK<<1)
	LDI ZH, HIGH(USB_TICK<<1)

	CALL STRING_COMPARE_P

	BREQ IDLE_USB_PROCESS_CONTINUE

		

	IDLE_USB_PROCESS_CONTINUE:

	BUFFER_CLEAR USB_BUFFER_POINTER

	RET